Split check for better debugging

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -162,13 +162,20 @@ application_run_coupler:
     - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/simple_coupler_run" -n qubit_spectroscopy_vs_current
     # Read
     - ls .venv/lib/python3.10/site-packages/out
+    - echo "Listing all files under 'out':"
+    - find .venv/lib/python3.10/site-packages/out -type f -name "*.png"
     # Verify output
     - |
-      if find .venv/lib/python3.10/site-packages/out -type f | grep -q "qubit_spectroscopy_vs_current.png" && \
-        find .venv/lib/python3.10/site-packages/out -type f | grep -q "qubit_spectroscopy_vs_current_q14_q15_q15_spectroscopies.png"; then
-        echo "Both output files exist. Application ran successfully."
+      if find .venv/lib/python3.10/site-packages/out -type f | grep -q "qubit_spectroscopy_vs_current.png"; then
+        echo "Output file $OUTPUT_FILE exists. Application ran successfully."
       else
-        echo "Error: One or both output files not found."
+        echo "Error: Output file $OUTPUT_FILE not found."
+        exit 1
+      fi
+      if find .venv/lib/python3.10/site-packages/out -type f | grep -q "qubit_spectroscopy_vs_current_q14_q15_q15_spectroscopies.png"; then
+        echo "Output file $OUTPUT_FILE exists. Application ran successfully."
+      else
+        echo "Error: Output file $OUTPUT_FILE not found."
         exit 1
       fi
   cache:
@@ -178,3 +185,7 @@ application_run_coupler:
     - key: "venv-${CI_COMMIT_REF_NAME}"
       paths:
         - .venv
+  artifacts:
+    paths:
+      - .venv/lib/python3.10/site-packages/out/
+    expire_in: 1 hour
