test: test draft data browser pipeline stage

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -14,11 +14,11 @@
 
 stages:
   - setup
-  - tests
-  - lint
-  - build_documentation
-  - application_run
-  - application_run_coupler
+#  - tests
+#  - lint
+#  - build_documentation
+#  - application_run
+#  - application_run_coupler
 
 variables:
   PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
@@ -45,177 +45,211 @@ setup:
       paths:
         - .venv
 
-tests:
-  stage: tests
-  image: python:${PYTHON_VERSION}
-  needs:
-    - setup
-  script:
-    # Install dependencies
-    - apt-get update
-    - apt-get install redis ffmpeg libsm6 libxext6 -y
-    # Run Redis server
-    - redis-server --daemonize yes --port "$REDIS_PORT"
-    # Activate the virtual environment
-    - source .venv/bin/activate
-    # Run tests
-    - pytest tergite_autocalibration --cov=tergite_autocalibration --cov-report xml --cov-report term-missing --junitxml=report.xml
-  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
-  artifacts:
-    reports:
-      junit: report.xml
-      coverage_report:
-        coverage_format: cobertura
-        path: coverage.xml
-  cache:
-    - key: "default"
-      paths:
-        - .cache/pip
-    - key: "venv-${CI_COMMIT_REF_NAME}"
-      paths:
-        - .venv
+#tests:
+#  stage: tests
+#  image: python:${PYTHON_VERSION}
+#  needs:
+#    - setup
+#  script:
+#    # Install dependencies
+#    - apt-get update
+#    - apt-get install redis ffmpeg libsm6 libxext6 -y
+#    # Run Redis server
+#    - redis-server --daemonize yes --port "$REDIS_PORT"
+#    # Activate the virtual environment
+#    - source .venv/bin/activate
+#    # Run tests
+#    - pytest tergite_autocalibration --cov=tergite_autocalibration --cov-report xml --cov-report term-missing --junitxml=report.xml
+#  coverage: '/TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
+#  artifacts:
+#    reports:
+#      junit: report.xml
+#      coverage_report:
+#        coverage_format: cobertura
+#        path: coverage.xml
+#  cache:
+#    - key: "default"
+#      paths:
+#        - .cache/pip
+#    - key: "venv-${CI_COMMIT_REF_NAME}"
+#      paths:
+#        - .venv
+#
+#build_documentation:
+#  stage: build_documentation
+#  image: python:${PYTHON_VERSION}
+#  needs:
+#    - setup
+#  script:
+#    # Activate the virtual environment
+#    - source .venv/bin/activate
+#    # Install documentation dependencies
+#    - pip install '.[docs]'
+#    # Build the documentation with strict mode to catch warnings and errors
+#    - mkdocs build --strict
+#  cache:
+#    - key: "default"
+#      paths:
+#        - .cache/pip
+#    - key: "venv-${CI_COMMIT_REF_NAME}"
+#      paths:
+#        - .venv
+#
+#lint:
+#  stage: lint
+#  image: python:${PYTHON_VERSION}
+#  needs:
+#    - setup
+#  script:
+#    # Activate the virtual environment
+#    - source .venv/bin/activate
+#    # Run linter and make it fail under 7.0
+#    - pylint tergite_autocalibration --fail-under=7.0
+#    # Run formatter
+#    - black --check tergite_autocalibration
+#  cache:
+#    - key: "default"
+#      paths:
+#        - .cache/pip
+#    - key: "venv-${CI_COMMIT_REF_NAME}"
+#      paths:
+#        - .venv
+#
+#application_run:
+#  stage: application_run
+#  image: python:${PYTHON_VERSION}
+#  needs:
+#    - setup
+#    - tests
+#  script:
+#    # Install dependencies
+#    - apt-get update
+#    - apt-get install redis ffmpeg libsm6 libxext6 -y
+#    # Run Redis server
+#    - redis-server --daemonize yes --port "$REDIS_PORT"
+#    # Activate the virtual environment
+#    - source .venv/bin/activate
+#    # Create empty .env file
+#    - touch .env
+#    # Load configuration
+#    - echo "y" | acli config load -t fc8a
+#    # Reset Redis
+#    - echo "y" | acli node reset -a
+#    # Clear the caches
+#    - rm -r .venv/lib/python3.12/site-packages/out
+#    # Run the calibration chain
+#    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n resonator_spectroscopy
+#    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n qubit_01_spectroscopy
+#    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n rabi_oscillations
+#    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n ramsey_correction
+#    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n motzoi_parameter
+#    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n n_rabi_oscillations
+#    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n resonator_spectroscopy_1
+#    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n qubit_12_spectroscopy
+#    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n rabi_oscillations_12
+#    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n ramsey_correction_12
+#    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n motzoi_parameter_12
+#    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n n_rabi_oscillations_12
+#    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n resonator_spectroscopy_2
+#    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n ro_frequency_three_state_optimization
+#    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n ro_amplitude_three_state_optimization
+#    # Read
+#    - ls -lR .venv/lib/python3.12/site-packages/out
+#    # Delay to encounter for the race condition
+#    - sleep 5
+#    # Verify output
+#    - |
+#      if find .venv/lib/python3.12/site-packages/out -type f | grep -q "ro_amplitude_three_state_optimization.png"; then
+#        echo "Output file $OUTPUT_FILE exists. Application ran successfully."
+#      else
+#        echo "Error: Output file $OUTPUT_FILE not found."
+#        exit 1
+#      fi
+#  cache:
+#    - key: "default"
+#      paths:
+#        - .cache/pip
+#    - key: "venv-${CI_COMMIT_REF_NAME}"
+#      paths:
+#        - .venv
+#
+#application_run_coupler:
+#  stage: application_run_coupler
+#  image: python:${PYTHON_VERSION}
+#  needs:
+#    - setup
+#    - tests
+#  script:
+#    # Install dependencies
+#    - apt-get update
+#    - apt-get install redis ffmpeg libsm6 libxext6 -y
+#    # Run Redis server
+#    - redis-server --daemonize yes --port "$REDIS_PORT"
+#    # Activate the virtual environment
+#    - source .venv/bin/activate
+#    # Create empty .env file
+#    - touch .env
+#    # Load configuration
+#    - echo "y" | acli config load -t fc8a
+#    # Reset Redis
+#    - echo "y" | acli node reset -a
+#    # Clear the caches
+#    - rm -r .venv/lib/python3.12/site-packages/out
+#    # Run the calibration chain
+#    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/simple_coupler_run" -n resonator_spectroscopy_vs_current
+#    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/simple_coupler_run" -n qubit_spectroscopy_vs_current
+#    # Read
+#    - ls .venv/lib/python3.12/site-packages/out
+#    - echo "Listing all files under 'out':"
+#    - find .venv/lib/python3.12/site-packages/out -type f -name "*.png"
+#    # Verify output
+#    - |
+#      if find .venv/lib/python3.12/site-packages/out -type f | grep -q "qubit_spectroscopy_vs_current.png"; then
+#        echo "Output file $OUTPUT_FILE exists. Application ran successfully."
+#      else
+#        echo "Error: Output file $OUTPUT_FILE not found."
+#        exit 1
+#      fi
+#      if find .venv/lib/python3.12/site-packages/out -type f | grep -q "qubit_spectroscopy_vs_current_q14_q15_q15_spectroscopies.png"; then
+#        echo "Output file $OUTPUT_FILE exists. Application ran successfully."
+#      else
+#        echo "Error: Output file $OUTPUT_FILE not found."
+#        exit 1
+#      fi
+#  cache:
+#    - key: "default"
+#      paths:
+#        - .cache/pip
+#    - key: "venv-${CI_COMMIT_REF_NAME}"
+#      paths:
+#        - .venv
 
-build_documentation:
-  stage: build_documentation
+browser_run:
+  stage: browser_run
   image: python:${PYTHON_VERSION}
   needs:
     - setup
   script:
     # Activate the virtual environment
     - source .venv/bin/activate
-    # Install documentation dependencies
-    - pip install '.[docs]'
-    # Build the documentation with strict mode to catch warnings and errors
-    - mkdocs build --strict
-  cache:
-    - key: "default"
-      paths:
-        - .cache/pip
-    - key: "venv-${CI_COMMIT_REF_NAME}"
-      paths:
-        - .venv
-
-lint:
-  stage: lint
-  image: python:${PYTHON_VERSION}
-  needs:
-    - setup
-  script:
-    # Activate the virtual environment
-    - source .venv/bin/activate
-    # Run linter and make it fail under 7.0
-    - pylint tergite_autocalibration --fail-under=7.0
-    # Run formatter
-    - black --check tergite_autocalibration
-  cache:
-    - key: "default"
-      paths:
-        - .cache/pip
-    - key: "venv-${CI_COMMIT_REF_NAME}"
-      paths:
-        - .venv
-
-application_run:
-  stage: application_run
-  image: python:${PYTHON_VERSION}
-  needs:
-    - setup
-    - tests
-  script:
-    # Install dependencies
-    - apt-get update
-    - apt-get install redis ffmpeg libsm6 libxext6 -y
-    # Run Redis server
-    - redis-server --daemonize yes --port "$REDIS_PORT"
-    # Activate the virtual environment
-    - source .venv/bin/activate
-    # Create empty .env file
-    - touch .env
+    # Copy the .env file
+    - cp .example.env .env
     # Load configuration
     - echo "y" | acli config load -t fc8a
-    # Reset Redis
-    - echo "y" | acli node reset -a
-    # Clear the caches
-    - rm -r .venv/lib/python3.12/site-packages/out
-    # Run the calibration chain
-    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n resonator_spectroscopy
-    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n qubit_01_spectroscopy
-    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n rabi_oscillations
-    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n ramsey_correction
-    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n motzoi_parameter
-    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n n_rabi_oscillations
-    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n resonator_spectroscopy_1
-    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n qubit_12_spectroscopy
-    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n rabi_oscillations_12
-    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n ramsey_correction_12
-    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n motzoi_parameter_12
-    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n n_rabi_oscillations_12
-    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n resonator_spectroscopy_2
-    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n ro_frequency_three_state_optimization
-    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/standard_run-ro_amplitude_three_state_optimization" -n ro_amplitude_three_state_optimization
-    # Read
-    - ls -lR .venv/lib/python3.12/site-packages/out
-    # Delay to encounter for the race condition
-    - sleep 5
+    # Start the data browser
+    - acli browser start
+    # Delay to give the browser some time to start
+    - sleep 15
     # Verify output
     - |
-      if find .venv/lib/python3.12/site-packages/out -type f | grep -q "ro_amplitude_three_state_optimization.png"; then
-        echo "Output file $OUTPUT_FILE exists. Application ran successfully."
+      if curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8178 | grep -q 200; then
+        echo "Data browser is running on port 8178"
       else
-        echo "Error: Output file $OUTPUT_FILE not found."
+        echo "Data browser is not running on port 8178"
         exit 1
       fi
-  cache:
-    - key: "default"
-      paths:
-        - .cache/pip
-    - key: "venv-${CI_COMMIT_REF_NAME}"
-      paths:
-        - .venv
-
-application_run_coupler:
-  stage: application_run_coupler
-  image: python:${PYTHON_VERSION}
-  needs:
-    - setup
-    - tests
-  script:
-    # Install dependencies
-    - apt-get update
-    - apt-get install redis ffmpeg libsm6 libxext6 -y
-    # Run Redis server
-    - redis-server --daemonize yes --port "$REDIS_PORT"
-    # Activate the virtual environment
-    - source .venv/bin/activate
-    # Create empty .env file
-    - touch .env
-    # Load configuration
-    - echo "y" | acli config load -t fc8a
-    # Reset Redis
-    - echo "y" | acli node reset -a
-    # Clear the caches
-    - rm -r .venv/lib/python3.12/site-packages/out
-    # Run the calibration chain
-    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/simple_coupler_run" -n resonator_spectroscopy_vs_current
-    - echo "n" | acli start -r "$CI_PROJECT_DIR/tergite_autocalibration/tests/fixtures/data/simple_coupler_run" -n qubit_spectroscopy_vs_current
-    # Read
-    - ls .venv/lib/python3.12/site-packages/out
-    - echo "Listing all files under 'out':"
-    - find .venv/lib/python3.12/site-packages/out -type f -name "*.png"
-    # Verify output
-    - |
-      if find .venv/lib/python3.12/site-packages/out -type f | grep -q "qubit_spectroscopy_vs_current.png"; then
-        echo "Output file $OUTPUT_FILE exists. Application ran successfully."
-      else
-        echo "Error: Output file $OUTPUT_FILE not found."
-        exit 1
-      fi
-      if find .venv/lib/python3.12/site-packages/out -type f | grep -q "qubit_spectroscopy_vs_current_q14_q15_q15_spectroscopies.png"; then
-        echo "Output file $OUTPUT_FILE exists. Application ran successfully."
-      else
-        echo "Error: Output file $OUTPUT_FILE not found."
-        exit 1
-      fi
+    # Stop the browser again
+    - acli browser stop
   cache:
     - key: "default"
       paths:
